import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright-core';

const browser = await chromium.launch({
  headless: true,
  executablePath: process.env.PLAYWRIGHT_EXECUTABLE_PATH || (process.platform === 'win32' ? 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' : undefined),
  args: ['--disable-gpu'],
});
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
page.on('console', (entry) => { if (entry.type() === 'error') errors.push(entry.text()); });
await page.route('**/api/contents', async (route) => {
  const request = route.request();
  if (request.method() !== 'POST') return route.continue();
  const payload = request.postDataJSON();
  const now = new Date().toISOString();
  return route.fulfill({
    status: 201,
    contentType: 'application/json',
    body: JSON.stringify({
      content: {
        id: 'topic-e2e-content',
        name: payload.name,
        platform: payload.platform,
        materialIds: payload.materialIds || [],
        createdAt: now,
        updatedAt: now,
        status: 'saved',
        versions: [{ ...payload, id: 'topic-e2e-version', createdAt: now }],
      },
    }),
  });
});

await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle', timeout: 15000 });
await page.evaluate(() => {
  localStorage.clear();
  localStorage.setItem('contentflow-chat-cleared-20260815', '1');
  localStorage.setItem('contentflow-v1-draft', JSON.stringify({
    platform: 'xiaohongshu',
    tone: '自然、专业',
    dirty: false,
    messages: [{ id: 'topic-e2e-user', role: 'user', text: '写一篇小红书产品介绍' }],
    result: {
      resultId: 'topic-e2e-result',
      taskId: 'topic-e2e-task',
      platform: 'xiaohongshu',
      platformMode: 'note',
      titleCandidates: [
        'AI 求职助手，自动投递省时间',
        'Tlink 把重复投递交给 AI',
        '求职时间不该浪费在重复投递上',
      ],
      selectedTitleIndex: 0,
      summary: null,
      bodyMarkdown: '产品名是 Tlink，它面向需要处理大量岗位信息的求职者，把重复的 AI 求职和简历投递交给工具处理。\n\n求职过程中，真正需要人做判断的是岗位是否匹配、公司是否值得了解，以及面试前该准备什么。如果时间大量消耗在重复填写和投递上，这些更重要的判断就容易被挤压。\n\nTlink 的作用不是替用户决定要投什么岗位，而是承接已经确认后的重复操作。用户仍然掌握岗位选择和投递节奏，工具只处理明确的执行环节。\n\n这样的边界更适合已经有求职方向、但需要持续跟进多个岗位的人。它减少的是重复执行成本，留给用户的仍然是必须由自己完成的选择和判断。',
      topics: [],
      qualityReport: {
        status: 'blocked',
        platformCheck: 'blocked',
        blockingErrors: ['缺少必需字段：topics', 'topics 至少需要 3 项'],
        warnings: [],
      },
    },
  }));
});
await page.reload({ waitUntil: 'networkidle' });

const chipTexts = () => page.locator('.topic-chip').allTextContents();
const topicCount = () => page.locator('.topic-count').innerText();
const openTopicInput = async () => {
  await page.locator('.custom-topic-button').click();
  const input = page.locator('.custom-topic-input');
  await input.waitFor({ state: 'visible' });
  return input;
};

await page.waitForFunction(() => document.querySelectorAll('.topic-chip').length >= 3);
const initial = await chipTexts();
const autoGenerated = initial.includes('#Tlink') && initial.includes('#AI求职') && initial.includes('#简历投递');
const internalBlockHidden = !(await page.locator('.quality-trigger').innerText()).includes('需要确认');
const copyButton = page.locator('.copy-result-button');
const iconOnlyCopy = (await copyButton.innerText()).trim() === '' && await copyButton.getAttribute('aria-label') === '复制全文';
const bodyLabel = page.locator('.body-field > .result-field-label');
await bodyLabel.scrollIntoViewIfNeeded();
const bodyLabelBeforeScroll = await bodyLabel.evaluate((element) => ({
  position: getComputedStyle(element).position,
  top: element.getBoundingClientRect().top,
}));
const scrollBefore = await page.locator('.conversation').evaluate((element) => element.scrollTop);
await page.locator('.conversation').evaluate((element) => { element.scrollTop += 160; });
await page.waitForTimeout(100);
const scrollAfter = await page.locator('.conversation').evaluate((element) => element.scrollTop);
const bodyLabelAfterScroll = await bodyLabel.evaluate((element) => element.getBoundingClientRect().top);
const bodyHeaderNotSticky = bodyLabelBeforeScroll.position === 'static'
  && scrollAfter > scrollBefore
  && bodyLabelAfterScroll < bodyLabelBeforeScroll.top - 100;
let topicInput = await openTopicInput();
await topicInput.fill('效率工具');
await topicInput.press('Enter');
await page.waitForFunction(() => document.querySelectorAll('.topic-chip').length >= 4);

topicInput = await openTopicInput();
await topicInput.fill('AI求职');
await topicInput.press('Enter');
const duplicateIgnored = (await page.locator('.topic-chip').allTextContents()).filter((item) => item === '#AI求职').length === 1;
const customAdded = (await chipTexts()).includes('#效率工具');

await page.locator('.topic-chip').first().locator('.arco-tag-close-btn').click();
const removed = !(await chipTexts()).includes(initial[0]);
await page.waitForTimeout(3500);
const autoSaved = (await page.locator('.save-state-tag').innerText()).includes('已自动保存');

fs.mkdirSync(path.resolve('screenshots'), { recursive: true });
await page.locator('.topic-field').scrollIntoViewIfNeeded();
await page.screenshot({ path: path.resolve('screenshots', 'topic-tags-desktop.png'), fullPage: false });
await page.locator('.result-actions').scrollIntoViewIfNeeded();
await page.screenshot({ path: path.resolve('screenshots', 'copy-icon-footer.png'), fullPage: false });
const desktop = await page.evaluate(() => {
  const field = document.querySelector('.topic-chip-editor');
  const styles = getComputedStyle(field);
  return {
    minHeight: parseFloat(styles.minHeight),
    scrollWidth: document.documentElement.scrollWidth,
    clientWidth: document.documentElement.clientWidth,
  };
});

await page.setViewportSize({ width: 390, height: 844 });
await page.locator('.topic-field').scrollIntoViewIfNeeded();
await page.screenshot({ path: path.resolve('screenshots', 'topic-tags-mobile.png'), fullPage: false });
const mobile = await page.evaluate(() => ({
  scrollWidth: document.documentElement.scrollWidth,
  clientWidth: document.documentElement.clientWidth,
  fieldWidth: document.querySelector('.topic-chip-editor').getBoundingClientRect().width,
  parentWidth: document.querySelector('.topic-field').getBoundingClientRect().width,
}));

await page.setViewportSize({ width: 1440, height: 960 });
const platformCases = [
  { platform: 'xiaohongshu', label: '话题', placeholder: '添加小红书话题', count: '3/8', chips: ['#AI求职', '#简历投递', '#效率工具'] },
  { platform: 'zhihu', label: '关联话题', placeholder: '添加知乎话题', count: '3/5', chips: ['AI求职', '简历投递', '效率工具'] },
  { platform: 'wechat', label: '文章标签', placeholder: '添加公众号文章标签', count: '3/5', chips: ['AI求职', '简历投递', '效率工具'] },
  { platform: 'generic', label: '关键词', placeholder: '添加内容关键词', count: '3/8', chips: ['AI求职', '简历投递', '效率工具'] },
];
const platformVariants = {};
for (const platformCase of platformCases) {
  await page.evaluate(({ platform }) => {
    const draft = JSON.parse(localStorage.getItem('contentflow-v1-draft'));
    draft.platform = platform;
    draft.result.platform = platform;
    draft.result.topics = ['AI求职', '简历投递', '效率工具'];
    localStorage.setItem('contentflow-v1-draft', JSON.stringify(draft));
  }, platformCase);
  await page.reload({ waitUntil: 'networkidle' });
  const field = page.locator(`.topic-field.topic-platform-${platformCase.platform}`);
  await field.waitFor({ state: 'visible' });
  await field.scrollIntoViewIfNeeded();
  const variant = await field.evaluate((element) => {
    const input = element.querySelector('input');
    return {
      label: element.querySelector('.topic-field-title')?.childNodes[0]?.textContent,
      count: element.querySelector('.topic-count')?.textContent,
      chips: [...element.querySelectorAll('.topic-chip .arco-tag-content')].map((chip) => chip.textContent),
      accent: getComputedStyle(element).getPropertyValue('--topic-accent').trim(),
      chipBackground: getComputedStyle(element.querySelector('.topic-chip')).backgroundColor,
    };
  });
  await page.screenshot({ path: path.resolve('screenshots', `topic-tags-${platformCase.platform}.png`), fullPage: false });
  await field.locator('.custom-topic-button').click();
  variant.placeholder = await field.locator('.custom-topic-input').getAttribute('placeholder');
  platformVariants[platformCase.platform] = variant;
}
const platformVariantsValid = platformCases.every((platformCase) => {
  const variant = platformVariants[platformCase.platform];
  return variant.label === platformCase.label
    && variant.placeholder === platformCase.placeholder
    && variant.count === platformCase.count
    && JSON.stringify(variant.chips) === JSON.stringify(platformCase.chips);
});
const platformAccentsDistinct = new Set(Object.values(platformVariants).map((variant) => variant.accent)).size === platformCases.length;
const platformChipStylesDistinct = new Set(Object.values(platformVariants).map((variant) => variant.chipBackground)).size === platformCases.length;

const result = {
  initial,
  autoGenerated,
  internalBlockHidden,
  iconOnlyCopy,
  bodyHeaderNotSticky,
  customAdded,
  duplicateIgnored,
  removed,
  autoSaved,
  desktop,
  mobile,
  platformVariants,
  platformVariantsValid,
  platformAccentsDistinct,
  platformChipStylesDistinct,
  errors,
};
console.log(JSON.stringify(result, null, 2));
await browser.close();

if (
  !autoGenerated
  || !internalBlockHidden
  || !iconOnlyCopy
  || !bodyHeaderNotSticky
  || !customAdded
  || !duplicateIgnored
  || !removed
  || !autoSaved
  || desktop.minHeight < 46
  || desktop.scrollWidth > desktop.clientWidth
  || mobile.scrollWidth > mobile.clientWidth
  || mobile.fieldWidth > mobile.parentWidth
  || !platformVariantsValid
  || !platformAccentsDistinct
  || !platformChipStylesDistinct
  || errors.length
) process.exit(1);
