import { chromium } from 'playwright-core';

const browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_EXECUTABLE_PATH || (process.platform === 'win32' ? 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' : undefined), args: ['--disable-gpu', '--no-first-run'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
page.setDefaultTimeout(5000);
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
page.on('console', (entry) => { if (entry.type() === 'error') errors.push(entry.text()); });
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded' });
console.log('stage:loaded');
await page.waitForSelector('#root .app-shell');
await page.getByRole('button', { name: /质量检查/ }).click();
console.log('stage:drawer-open');
await page.waitForSelector('.qa-drawer');
const drawerVisible = await page.locator('.qa-drawer').isVisible();
await page.keyboard.press('Escape');
await page.waitForSelector('.qa-drawer', { state: 'hidden' });
console.log('stage:drawer-closed');
await page.getByRole('button', { name: '知乎' }).click();
console.log('stage:zhihu');
const zhihuVisible = await page.getByText('让 AI 参与复杂业务系统开发，真正困难的是什么？', { exact: true }).first().isVisible();
await page.getByRole('button', { name: '生成发布包' }).click();
console.log('stage:delivered');
await page.waitForTimeout(200);
const delivered = await page.getByText('已交付', { exact: true }).isVisible();
const metrics = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }));
console.log(JSON.stringify({ drawerVisible, zhihuVisible, delivered, metrics, errors }, null, 2));
await Promise.race([browser.close(), new Promise((resolve) => setTimeout(resolve, 1200))]);
if (!drawerVisible || !zhihuVisible || !delivered || metrics.scrollWidth > metrics.clientWidth || errors.length) process.exit(1);
process.exit(0);
